// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymaJgCZysItCRJAmSB88lrM7N1kl2pks',
    appId: '1:869960451500:web:c6e45b1261ea76e71c2609',
    messagingSenderId: '869960451500',
    projectId: 'share-ideas-a6f23',
    authDomain: 'share-ideas-a6f23.firebaseapp.com',
    storageBucket: 'share-ideas-a6f23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Vwn_SCnLkZZYVRCM4ad2EfTCqwu7j6I',
    appId: '1:869960451500:android:66c9cd67ef7cf5c11c2609',
    messagingSenderId: '869960451500',
    projectId: 'share-ideas-a6f23',
    storageBucket: 'share-ideas-a6f23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChn8myh0QeYwh4CtIts0xrNN6C-n2ZE4g',
    appId: '1:869960451500:ios:5684de5bb054e0361c2609',
    messagingSenderId: '869960451500',
    projectId: 'share-ideas-a6f23',
    storageBucket: 'share-ideas-a6f23.appspot.com',
    iosClientId: '869960451500-1qn07icis472267nqjddlc2v1i6g0cs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareIdeas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChn8myh0QeYwh4CtIts0xrNN6C-n2ZE4g',
    appId: '1:869960451500:ios:5684de5bb054e0361c2609',
    messagingSenderId: '869960451500',
    projectId: 'share-ideas-a6f23',
    storageBucket: 'share-ideas-a6f23.appspot.com',
    iosClientId: '869960451500-1qn07icis472267nqjddlc2v1i6g0cs1.apps.googleusercontent.com',
    iosBundleId: 'com.example.shareIdeas',
  );
}
